version: '3.7'

services:
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: my_blog
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'

volumes:
  data:
    driver: local

networks:
    default:
        name: server_internal
        external: true
